### ISSUE TITLE
Glitch with curios

### ISSUE THREAD

**Issue by aaronneedshelpo** [GoryMoon/Chargers#10]
Requiring Curios 4.0.0.1 and when I provide that it says that it's wrong... But then when I install Curios 4.0.3.0 (NEWER) because it says it required Curios 4.0.0.1 IT STILL DIDNT WORK

**Comment by GoryMoon** [comment]
Uploaded a new version with the fix https://www.curseforge.com/minecraft/mc-mods/chargers/files/3378540
