### ISSUE TITLE
Strange interaction with Baubles

### ISSUE THREAD

**Issue by MightyBidoof** [GoryMoon/Chargers#2]
I added this mod to my modded Skyblock simply as a way of powering Building Gadgets, and it has quite a strange interaction with Baubles:

For some reason it blocks the initial scanning for equipped Baubles, so you have to manually enter the baubles menu to update it, and it also blocks some baubles from working (e.g Botania's Invisibility Cape wouldn't apply invisibility despite me having a full mana tablet in my inventory)

It also blocked damage sounds on the player for some reason. (e.g being hit by a zombie wouldn't make any noise, but damage would still be applied)

**Comment by GoryMoon** [comment]
Can't reproduce any of these issues in dev, did you test with the minimum amount of mods needed?
I have Chargers, Baubles, Botania and Cyclic
