### ISSUE TITLE
Request: Power drainers

### ISSUE THREAD

**Issue by brooswit** [GoryMoon/Chargers#24]
I'd like to use the following mods together:

https://www.curseforge.com/minecraft/mc-mods/energeticsheep
https://www.curseforge.com/minecraft/mc-mods/create
https://www.curseforge.com/minecraft/mc-mods/createaddition

I'd like to use energetic sheep to electrically power create machines using createadditions motor. The only problem is that I have no way to drain the power from the electrically charged wool.

I love this mod, and how it simply adds chargers. I'd love if you also added drainers, so one could drain power from items to generate power.

**Comment by GoryMoon** [comment]
If you put an item in the slot below the power it will discharge that item.
It should be automatable by inserting and extracting from the side. It should only allow to pull if the item is empty.
Let me know if this doesn't solve your issue.
