### ISSUE TITLE
Please update Curios requirement

### ISSUE THREAD

**Issue by Serifina** [GoryMoon/Chargers#8]
When trying to start Minecraft with the most recent Curios, it complains that it needs Curios of 4.0.0.1... even though I'm running Curios 4.0.5.1.

**Comment by christianbutnot** [comment]
Kind of urgent needed fix for this to be honest. I would update it myself if permission is given. People are finding a workaround by editing the mod.toml but can't justify doing such for a modpack without permission.

**Comment by ChipmunkCraft** [comment]
Just a heads up for those wondering why the response is lacking.  I haven't seen GoryMoon around for awhile and his last communication on Darkosto's discord channel was January 24th.

Chances are, Gory hasn't been able to get online or look at anything.

I agree it is an urgently needed fix, but we need to be patient.

**Update:** I've provided a fix on my forked version and have put in a pull request to get it in the main repository.  Hopefully they can get it merged soon. (Or do the fix themselves)

**Comment by GoryMoon** [comment]
Uploaded a new version with the fix https://www.curseforge.com/minecraft/mc-mods/chargers/files/3378540
